### PR TITLE
Add pipeline support

### PR DESCRIPTION
**Pull request by uglide**

### CODE REVIEW

**Comment by kplindegaard** [comment]
@uglide Thanks for following up so quickly.
I've updated my appveyor script (using Qt 5.9.7 and Visual Studio 2017) to also install Redis for Windows v3.2 and execute all integration tests and merged your feature/pipeline branch into my branch [ugilde/pipeline-appveyor](https://github.com/kplindegaard/qredisclient/tree/uglide/pipeline-appveyor). Unfortunately [it doesn't pass](https://ci.appveyor.com/project/kplindegaard/qredisclient/builds/21345317) through. 
[Build status](https://ci.appveyor.com/project/kplindegaard/qredisclient/branch/uglide/pipeline-appveyor)
Core dump in TestConnection::benchmarkPipeline() and TestConnection::benchmarkPipelineAsync() never ran, but the two shorter tests runPipelineCommand() and runPipelineCommansAsync() passed OK.

However, running the integration tests in Appveyor with yesterdays PR and its naive response handling, , which is in my [appveyor-pipeline](https://github.com/kplindegaard/qredisclient/tree/uglide/pipeline-appveyor) branch seems to pass through. 
[Build status](https://ci.appveyor.com/project/kplindegaard/qredisclient/branch/appveyor-pipeline).

Sorry about the verbose builds logs in both of them. I ended up running tests.exe with option -vs to just get an idea about raised signals. That should be skipped again for clarity later.

I fully support scrapping the PipelineTransporter class and the extra fuzz that went along with it. Will try to have a look at this during the weekend unless you have already solved it by then ;)

**Comment by uglide** [comment]
@kplindegaard That's interesting because it works on my Linux laptop. I will try to debug it on slower hardware.

**Comment by kplindegaard** [comment]
Did a quick test on a Win10 box with Redis 5.0 in a Docker container, and it seems that reading everything from the socket in one go in AbstractTransporter::readyRead() is errorprone for long response telegrams which will be chopped somewhere in the middle. We cannot guarantee that the stream breaks off after "\r\n" but could be right in the middle of a "+QUEUED\r\n" like this dump shows:

```
QDEBUG : TestConnection::benchmarkPipeline() readFromSocket:
 "\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+
QDEBUG : TestConnection::benchmarkPipeline() Start of reponse:  "QUE"
QDEBUG : TestConnection::benchmarkPipeline() hiredis cannot parse buffer Protocol error, got "Q" as reply type byte
QDEBUG : TestConnection::benchmarkPipeline() current buffer: ""
QDEBUG : TestConnection::benchmarkPipeline() all buffer: "QUEUED\x00\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QUEUED\r\n+QU
```

The first qDebug() is the buffer returned from DefaultTransporter::readFromSocket(), so you see this 3rd section of the full response starts with an illegal character. Then everything breaks down from there.

A quick but slow fix could be to not read beyond the last \n line:
```
QByteArray RedisClient::DefaultTransporter::readFromSocket() {
  QByteArray buf;
  while (m_socket->canReadLine())
      buf.append(m_socket->readLine());
  return buf;
  // return m_socket->readAll();
}
```
I'll try this just for the record. If successful, the first appveyor tag that was be read in a comment above should turn green.

**Comment by kplindegaard** [comment]
@uglide: I reverted my temporary `m_socket->readLine()` patch in DefaultTransporter after merging in your latest updates to my branch. [All unit tests pass](https://ci.appveyor.com/project/kplindegaard/qredisclient/builds/21401237) so the badge remains green :+1:

**Comment by uglide** [comment]
@kplindegaard I'm still is not satisfied with current implementation and still improving it.

**Comment by uglide** [comment]
@kplindegaard Thanks for all contributions and motivation to rewrite some old and dirty code :)

**Pull request merged**
